### PR TITLE
Final Pull for Sprint

### PR DESCRIPTION
**Pull request by alexMFuller**
General cleanup for sprint submission

### CODE REVIEW

**Review by Rloundy — APPROVED** [review]
The "Final" database document is outdated and the replacement is there so that needs to be deleted after that all looks good

**Comment by alexMFuller** [comment]
> The "Final" database document is outdated and the replacement is there so that needs to be deleted after that all looks good

fixed

**Comment by wardre** [comment]
> General cleanup for sprint submission

**Comment by wardre** [comment]
Looks good to merge

**Pull request merged**
