### PR TITLE
Alex dev

### PR DESCRIPTION
**Pull request by alexMFuller**

### CODE REVIEW

**Comment by alexMFuller** [comment]
This is a merge of all current branches out there and includes my  look and feel improvements. Please let me know if I messed up on the merges because I merged a lot into this pull

**Comment by alexMFuller** [comment]
Had issues merging Ronens, will review that merge later

**Review by pjhanks — COMMENTED** [review]
I don't see any issues. Good to merge.

**Comment by pjhanks** [comment]
Reviewed additional changes. Good to merge.

**Review by Rloundy — APPROVED** [review]
Looks Good

**Pull request merged**
