### PR TITLE
Patrick

### PR DESCRIPTION
**Pull request by pjhanks**
Initial unit tests for create Courses, Sections, TAs, TAAssignments. Updated models.py and Users.py.

### CODE REVIEW

**Review by Rloundy — COMMENTED** [review]
For models. we do not need a TA section lines 15-22, also line 35 should reference a user not the TA as it should be removed also line 25 representing the TAs in course should be removed.

**Comment by pjhanks** [comment]
Updated models.py per Rloundy's comments. Will merge pending an additional review.

**Comment by alexMFuller** [comment]
ClassTAAssignments can't reference TA anylonger as it does not exist, shoud be MyUser(?)

**Comment by alexMFuller** [comment]
Emails should also be able to be longer then 20 chars

**Comment by alexMFuller** [comment]
Pull request has been included in mass pull

**Pull request closed without merging**
